---
- hosts: default
  become: true
  tasks:
    - name: Update OS
      shell: yum update -y
    - name: Instal httpd
      yum:
        name: httpd
        state: latest
    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes